### ISSUE TITLE
天线部分不做阻抗匹配的话，不知道wifi性能影响大吗

### ISSUE THREAD

**Issue by Ncerzzk** [peng-zhihui/ESP32-PicoDK#1]
rt

**Comment by peng-zhihui** [comment]
pico d4的sip封装内是带射频匹配电路的，以前的仓库里已经说明过了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ncerzzk ***@***.***&gt;
发送时间: 2021年5月24日 16:32
收件人: peng-zhihui/ESP32-PicoDK ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[peng-zhihui/ESP32-PicoDK] 天线部分不做阻抗匹配的话，不知道wifi性能影响大吗 (#1)





 
rt

**Comment by Ncerzzk** [comment]
原来如此，谢谢回复
