### ISSUE TITLE
MPU的AD0和FSYNC引脚未接地

### ISSUE THREAD

**Issue by gleefish** [peng-zhihui/ESP32-PicoDK#10]
![i2c 设备地址](https://user-images.githubusercontent.com/75210521/122926911-ed06c400-d39a-11eb-95d4-c2ff86616668.png)
我试了几个MPU芯片读出来的地址都是0x69，然后数据只传输一组后保持不变。AD0接地的话，地址应该是0x68，不知道是否是AD0的影响，我买了MPU模块正在路上，准备排查一下是否是mpu故障还是AD0悬空导致的问题，大家有遇到类似问题嘛？谢谢

**Comment by gleefish** [comment]
查看pcb文件发现两个引脚未接地，修改后mpu正常工作，设备iic地址也正常显示为0x68，供大家参考。

**Comment by stig3** [comment]
同样的问题，数据只传输一组后保持不变，看到PCB上fsync那块是死铜，然后飞了跟线，让fsync接地，ad0悬空不影响，地址设置成0x69, 然后就工作正常了。
看了一下datasheet, 这个是同步信号，工作模式应该是收到低电平再更新数据
![image](https://user-images.githubusercontent.com/3666343/126583894-47cd9c06-7a9e-4ee2-8590-82141a97d66b.png)
如果悬空的话，那就不更新数据的，所以这个数据只传输一组后保持不变的问题应该就是fsync悬空导致的。

**Comment by peng-zhihui** [comment]
新版已经加上了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "peng-zhihui/ESP32-PicoDK"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月22日(星期四) 上午10:54
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [peng-zhihui/ESP32-PicoDK] MPU的AD0和FSYNC引脚未接地 (#10)





 
同样的问题，数据只传输一组后保持不变，看到PCB上fsync那块是死铜，然后飞了跟线，让fsync接地，ad0悬空不影响，地址设置成0x69, 然后就工作正常了。
 看了一下datasheet, 这个是同步信号，工作模式应该是收到低电平再更新数据
 
 如果悬空的话，那就不更新数据的，所以这个数据只传输一组后保持不变的问题应该就是fsync悬空导致的。
