### ISSUE TITLE
第一次烧录的后续烧录失败

### ISSUE THREAD

**Issue by nanshenwei** [peng-zhihui/ESP32-PicoDK#11]
焊接好IMU CP2102 ESP32以及必须的外围电路和烧录电路后，可以轻松成功烧录IMU例程，并成功运行程序，没有异常正常输出IMU信息。但是紧接着烧录第二次的时候（没有任何其他动作）会一直不能自动进入下载模式
尝试重新焊接  更换复位电路的0.1uF电容为1uF以及更换三极管12k电阻至1k都不能成功。更换新的ESP32芯片后仍然只能自动烧录第一次。

同时，无法通过复位按键复位（除非把复位按键的1k电阻换成0Ohm电阻），不知道是否有其他原因造成。

使用Arduino IDE进行的烧录

**Comment by nanshenwei** [comment]
只能通过烧录时手动短接IO0和GND进入下载模式

**Comment by nanshenwei** [comment]
1. 示波器看如果按照高电平为0.75*VDD的话理论上是没问题的，但不知道为什么芯片还是不认为EN上升沿的时候IO0是低电平。
2. 尝试把EN引脚电容0.1uF换成2.2uF（换成1uF之后结果为1.所描述的）就能自动下载了。
3. esptool.py这个脚本中升高EN的时候不延时等待IO0变为低电平，导致EN上升沿的过程中 ，IO0会有个矩形波（示波器显示的矩形波可能是这样产生的？）但是更改脚本无效，Arduino IDE应该是使用封装好的EXE文件运行的脚本，所以直接改脚本无效。

**Comment by uxfion** [comment]
按楼主的尝试把EN引脚电容0.1uF换成2.2uF，可以自动下载
