### ISSUE TITLE
没有找到PCB文件啊

### ISSUE THREAD

**Issue by mailonghua** [peng-zhihui/ESP32-PicoDK#19]
请教一下，PCB文件在仓库中没有看到，这个是没开出来吗

**Comment by JiaoLu-JNU** [comment]
不就在那吗

**Comment by mailonghua** [comment]
![image](https://user-images.githubusercontent.com/36437073/143872520-af4525f7-774d-442c-b153-08ffd1c1f690.png)
在哪里，从commit回退了一笔提交后，看到了pcb

**Comment by JiaoLu-JNU** [comment]
好像还真是

**Comment by peng-zhihui** [comment]
之前的提交错误，已修复

**Comment by wc7086** [comment]
> 之前的提交错误，已修复

并没有修复

**Comment by peng-zhihui** [comment]
再看看
