### ISSUE TITLE
尝试复现，并遇到问题，想请教下稚晖君及各位大佬

### ISSUE THREAD

**Issue by mmdjiji** [peng-zhihui/ESP32-PicoDK#20]
关于我的复现过程记录描述在这里：https://www.yuque.com/docs/share/f979c460-2324-497b-8bbf-e2ea19f214f1

目前：
- 供电正常，分别量了5V和3.3V
- CP2102识别了
- ESP32-PICO-D4没有识别
- GPIO0的电压为2.17V
- GPIO2的电压为1.06V

**Comment by peng-zhihui** [comment]
检查焊接，同时可以参考这个https://github.com/peng-zhihui/ESP32-PicoDK/issues/11

**Comment by mmdjiji** [comment]
复现成功了，感谢稚晖君，我换了张PICO按相同工艺焊接就ok了，所以怀疑是PICO因为未知原因损坏了。

效果如下：

![pic](https://s2.loli.net/2022/04/18/NPbtWh9aglE6pmj.jpg)

但是这个是我在关了全屋灯光之后照的，所以显示屏亮度过低，关于这个我怀疑是显示屏质量问题，打算再买一个显示屏换掉试试。

**Comment by peng-zhihui** [comment]
屏幕的电压检查一下，3.3V和5V是否正常

**Comment by mmdjiji** [comment]
检查了，3.3V和5V都是正常的

**Comment by mmdjiji** [comment]
后来换了个屏幕成功了，可见是屏幕质量问题。。。

![success.jpg](https://s2.loli.net/2022/04/21/Ww18SDOgCUReKYs.jpg)
