### ISSUE TITLE
立创EDA导入PCB失败

### ISSUE THREAD

**Issue by CodeChenL** [peng-zhihui/ESP32-PicoDK#23]
如图：
![image](https://user-images.githubusercontent.com/43897062/168442048-68ffc1ce-5b83-4a62-8c15-fca9df911f63.png)
![image](https://user-images.githubusercontent.com/43897062/168442053-2079a016-2380-4d79-b5bc-67f93e871ca0.png)

**Comment by CodeChenL** [comment]
![image](https://user-images.githubusercontent.com/43897062/168442099-4162e852-7c86-4bbc-81d4-aefc10527435.png)

**Comment by peng-zhihui** [comment]
本来就不是立创EDA画的，这不是已经提示你怎么操作了吗，自己操作一下就行啊。

**Comment by CodeChenL** [comment]
> 本来就不是立创EDA画的，这不是已经提示你怎么操作了吗，自己操作一下就行啊。

因为我的电脑是Linux的系统，所以跑ad不是很方便（
