### ISSUE TITLE
关于 A1 处陶瓷天线的型号问题

### ISSUE THREAD

**Issue by TPAXcc** [peng-zhihui/ESP32-PicoDK#26]
稚晖君，你在 A1 处的型号标识是不是弄错了啊，我在 [Rainsun 官网](www.rainsun.com/2-4ghz-5ghzwifi-蓝牙-zigbee天线系列/)也没找到 AN5120 啊，是不是 AN2051?

**Comment by donjion** [comment]
考虑用CrossAir 的CA-C03吧，看稚晖君实物图里也用的这个，Rainsun的天线太贵了hhh。[链接](http://www.gzhwjdz.com/ProductDetail/4411500.html)

**Comment by TPAXcc** [comment]
@donjion 没事，反正就就几块板🙃

**Comment by TPAXcc** [comment]
@donjion 没事，反正就就几块板🙃

**Comment by TPAXcc** [comment]
@donjion 实在不行也可以自己用铺铜做天线嘛(
