### ISSUE TITLE
arduino U8g2lib 报错

### ISSUE THREAD

**Issue by ka2223** [peng-zhihui/ESP32-PicoDK#27]
项目库文件夹里的 U8g2 放在C盘 Documents\Arduino\libraries ，也试过打包成ZIp在软件里添加，都是不行啊。
提示这个C:\Users\Jhin\Documents\Arduino\ESP32-OLED\ESP32-OLED.ino:3:21: fatal error: U8g2lib.h: No such file or directory

**Comment by hanchuangqj** [comment]
![mmexport1654588160545.jpg](https://user-images.githubusercontent.com/95151374/172325835-72e3d7f9-fe7d-4091-b536-22811465a021.jpg)
下载最新U8G2库

**Comment by ka2223** [comment]
> ![mmexport1654588160545.jpg](https://user-images.githubusercontent.com/95151374/172325835-72e3d7f9-fe7d-4091-b536-22811465a021.jpg) 下载最新U8G2库

下载了 还是报错哎 ，大神救救孩子吧

**Comment by hanchuangqj** [comment]
还得改下函数，之前那个是12864分辨率的呀，在最新库里可以找到sh1107的12880驱动



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月7日(周二) 下午3:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [peng-zhihui/ESP32-PicoDK] arduino U8g2lib 报错 (Issue #27)




  
 下载最新U8G2库
  
下载了 还是报错哎 ，大神救救孩子吧

**Comment by ka2223** [comment]
> 还得改下函数，之前那个是12864分辨率的呀，在最新库里可以找到sh1107的12880驱动
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年6月7日(周二) 下午3:53 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [peng-zhihui/ESP32-PicoDK] arduino U8g2lib 报错 (Issue #27) 下载最新U8G2库 下载了 还是报错哎 ，大神救救孩子吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

原来如此啊，感谢感谢O(∩_∩)O

**Comment by ka2223** [comment]
已解决
