### ISSUE TITLE
关于OLED屏幕VPP引脚电压过低的问题

### ISSUE THREAD

**Issue by JoeJoeOvO** [peng-zhihui/ESP32-PicoDK#29]
稚晖君您好，感谢您带来的一个个优秀的作品。
在最近复刻PicoDK的过程中，发现屏幕亮度较暗，难以看清内容。起初以为是焊接问题，排查后查阅了屏幕的数据手册，发现该**屏幕VPP引脚供电电压应为9V**，而在您的作品中是由VBUS直接供电，在大多数以TypeC供电的场景下，无法达到9V的要求，因此会影响显示效果。
同时，电源指示灯D1亮度似乎也有所偏高，导致在高亮LED下屏幕更加不易看清。
因此个人认为能否为屏幕驱动单独添加一个小型升压电路以满足屏幕驱动要求，同时增大LED串联电阻阻值从而减小亮度，可能会有更好的显示效果。
以上是我个人在学习过程中的一点想法，以供您参考，谢谢。

**Comment by peng-zhihui** [comment]
OLED 5V的亮度我觉得正好的，所以没加升压，你可以自己调整一下哈。

**Comment by JoeJoeOvO** [comment]
> OLED 5V的亮度我觉得正好的，所以没加升压，你可以自己调整一下哈。

好的。之前也有和许多遇到相同情况的小伙伴讨论过。看到这里没人提就来请教了一下。这里附上规格书里这款屏幕常用的升压驱动电路，当做是给其他小伙伴的小tips吧。
![2E3230LZSBN6`S)45YW132J](https://user-images.githubusercontent.com/85349898/184529165-2fd1fd89-487e-4341-8efe-a45d9a9dccd0.png)
将屏幕的VPP转接到9V输出端。
感谢稚晖君。
