### ISSUE TITLE
关于CC1/CC2 5.1K下拉电阻

### ISSUE THREAD

**Issue by fan-ziqi** [peng-zhihui/ESP32-PicoDK#5]
HoloCubic的TYPE-C没有下拉电阻也能正常工作，请问这个板子添加了这个电阻有什么作用啊

**Comment by peng-zhihui** [comment]
用于匹配c to c的数据线，使得pd充电器输出5v



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 范子琦 ***@***.***&gt;
发送时间: 2021年6月4日 10:23
收件人: peng-zhihui/ESP32-PicoDK ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[peng-zhihui/ESP32-PicoDK] 关于CC1/CC2 5.1K下拉电阻 (#5)





 
HoloCubic的TYPE-C没有下拉电阻也能正常工作，请问这个板子添加了这个电阻有什么作用啊

**Comment by fan-ziqi** [comment]
多谢！

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月7日 12:09:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [peng-zhihui/ESP32-PicoDK] 关于CC1/CC2 5.1K下拉电阻 (#5)




 用于匹配c to c的数据线，使得pd充电器输出5v 
 
 
 
 发自我的iPhone 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 范子琦 ***@***.***&amp;gt; 
 发送时间: 2021年6月4日 10:23 
 收件人: peng-zhihui/ESP32-PicoDK ***@***.***&amp;gt; 
 抄送: Subscribed ***@***.***&amp;gt; 
 主题: 回复：[peng-zhihui/ESP32-PicoDK] 关于CC1/CC2 5.1K下拉电阻 (#5) 
 
 
 
 
 
   
 HoloCubic的TYPE-C没有下拉电阻也能正常工作，请问这个板子添加了这个电阻有什么作用啊 
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;
