### ISSUE TITLE
关于2.Samples中CLion工程头文件找不到的问题

### ISSUE THREAD

**Issue by uxfion** [peng-zhihui/ESP32-PicoDK#7]
示例程序中PlatformIO中的CLion工程，无法找到头文件
```
#include <Arduino.h>
#include <U8g2lib.h>
#include <Wire.h>
```
如果自己新建esp32工程是能找到头文件的，但是在示例中无法找到
编译报错信息为
```
ESP32-PicoDK/2.Samples/PlatformIO/ESP32-OLED/lib/SimpleCLI/src/c/arg.c:7:20: fatal error: c/arg.h: No such file or directory
compilation terminated.
ESP32-PicoDK/2.Samples/PlatformIO/ESP32-OLED/lib/SimpleCLI/src/c/cmd.c:10:37: fatal error: c/comparator.h: No such file or directory
compilation terminated.
```
初步认为是SimpleCLI的问题（自己在此工程中是没有配置和使用过SimpleCLI的），希望大佬能给指明下处理这个问题的方向 @peng-zhihui

**Comment by peng-zhihui** [comment]
cmakelist里删掉这个库的引用就行了，这是我忘了删了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: FION ***@***.***&gt;
发送时间: 2021年6月9日 23:57
收件人: peng-zhihui/ESP32-PicoDK ***@***.***&gt;
抄送: 稚晖 ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[peng-zhihui/ESP32-PicoDK] 关于2.Samples中CLion工程头文件找不到的问题 (#7)





 
示例程序中PlatformIO中的CLion工程，无法找到头文件
 #include <Arduino.h&gt; #include <U8g2lib.h&gt; #include <Wire.h&gt;  
如果自己新建esp32工程是能找到头文件的，但是在示例中无法找到
 编译报错信息为
 ESP32-PicoDK/2.Samples/PlatformIO/ESP32-OLED/lib/SimpleCLI/src/c/arg.c:7:20: fatal error: c/arg.h: No such file or directory compilation terminated. ESP32-PicoDK/2.Samples/PlatformIO/ESP32-OLED/lib/SimpleCLI/src/c/cmd.c:10:37: fatal error: c/comparator.h: No such file or directory compilation terminated.  
初步认为是SimpleCLI的问题（自己在此工程中是没有配置和使用过SimpleCLI的），希望大佬能给指明下处理这个问题的方向 @peng-zhihui
