### ISSUE TITLE
关于MPU无法正常读取的问题

### ISSUE THREAD

**Issue by EListenX** [peng-zhihui/ESP32-PicoDK#9]
板载MPU无法正常工作，去掉跳线电阻，外挂模块模块可以正常工作，焊接在板子上就不行，只有在上电的一瞬间可以读取一个固定值，按下reset键，显示初始化失败，外挂模块则可以正常初始化，正常读取mpu的状态信息

**Comment by peng-zhihui** [comment]
检查焊接，或者买到假芯片了，我之前买过200多片坏的。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: EListen ***@***.***&gt;
发送时间: 2021年6月20日 15:36
收件人: peng-zhihui/ESP32-PicoDK ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[peng-zhihui/ESP32-PicoDK] 关于MPU无法正常读取的问题 (#9)

**Comment by EListenX** [comment]
![image](https://user-images.githubusercontent.com/79767780/123418269-70b6ef80-d5eb-11eb-97ed-6f940fde198e.png)
我想应该是电路问题 按照原理图几个引脚没有接地 新的issue也是反映的这个问题

**Comment by peng-zhihui** [comment]
那几个引脚不影响，已经好多人做好了没问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: EListen ***@***.***&gt;
发送时间: 2021年6月25日 19:30
收件人: peng-zhihui/ESP32-PicoDK ***@***.***&gt;
抄送: 稚晖 ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[peng-zhihui/ESP32-PicoDK] 关于MPU无法正常读取的问题 (#9)
